### ISSUE TITLE
Create JupyterLab operation fails with AttributeError

### ISSUE THREAD

**Issue by mboglesby** [NetApp/netapp-dataops-toolkit#13]
Running a 'create jupyterlab' operation with the NetApp DataOps Toolkit for Kubernetes fails with the following error:

```
(dtk-bug) moglesby@moglesby-mac-1 ~ % netapp_dataops_k8s_cli.py create jupyterlab -w ws1 -s 10Gi
Set workspace password (this password will be required in order to access the workspace):
Re-enter password:
Traceback (most recent call last):
  File "/Users/moglesby/venv/dtk-bug/bin/netapp_dataops_k8s_cli.py", line 787, in <module>
    create_jupyter_lab(workspace_name=workspaceName, workspace_size=workspaceSize, storage_class=storageClass,
  File "/Users/moglesby/venv/dtk-bug/lib/python3.9/site-packages/netapp_dataops/k8s/__init__.py", line 638, in create_jupyter_lab
    hashedPassword = IPython.lib.passwd(workspace_password)
AttributeError: module 'IPython.lib' has no attribute 'passwd'
```

**Comment by mboglesby** [comment]
This bug was introduced with version 8.0.0 of the ipython package. The IPython.lib.passwd attribute was removed. It will be fixed in an upcoming DataOps Toolkit release. In the meantime, a workaround is to force the installation of ipython version 7.32.0:

`python3 -m pip install --upgrade ipython==7.32.0`
